# azure-pipelines.yml

trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test Node.js 18 Application'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '18.x'
      checkLatest: true
    displayName: 'Use Node.js 18'

  - script: |
      npm install
    displayName: 'Install Dependencies'

  - script: |
      npm test
    displayName: 'Run Tests'

  - script: |
      npm run build
    displayName: 'Build Application'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Build.ArtifactStagingDirectory)'
      artifact: 'drop'
    displayName: 'Publish Build Artifacts'

- job: Deploy
  displayName: 'Deploy to Azure'
  dependsOn: BuildAndTest
  condition: succeeded()
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - download: current
    artifact: drop
    displayName: 'Download Build Artifacts'

  - task: AzureRmWebAppDeployment@4
    inputs:
      azureSubscription: '<Your Azure Subscription>'
      appType: 'webApp'
      WebAppName: '<Your Web App Name>'
      packageForLinux: '$(Pipeline.Workspace)/drop/**/*.zip'
    displayName: 'Deploy to Azure Web App'
